const { chromium } = await import("playwright");
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
page.on("pageerror", e => console.log("PAGEERROR", e.message));
await page.addInitScript(() => { try { localStorage.setItem("churchill_intro_seen_v1","1"); } catch {} });
await page.goto("http://localhost:8804/", { waitUntil: "load" });
await page.waitForFunction(() => !document.querySelector(".boot-screen"), null, { timeout: 30000 });
await page.waitForTimeout(2500);
console.log("btns0", await page.$$eval("button", bs => bs.map(b => b.className + " :: " + b.textContent.trim().slice(0,30))));
await page.locator(".mode", { hasText: "FREE ROAM" }).first().click();
await page.waitForTimeout(1500);
console.log("btns1", await page.$$eval("button", bs => bs.map(b => b.className + " :: " + b.textContent.trim().slice(0,30))));
await page.locator(".btn.gold").first().click();
await page.waitForTimeout(2000);
console.log("btns2", await page.$$eval("button", bs => bs.map(b => b.className + " :: " + b.textContent.trim().slice(0,30))));
console.log("overlay", await page.$$eval(".overlay", e => e.length));
await browser.close();
