#!/usr/bin/env python3
"""Emit the client's copy of the world's closed vocabularies.

`churchill/world/enums/` is the wire authority: the `Surface` values ARE the
bytes inside every tile's RLE, and every `StrEnum` here is a token the client
switches on. Until now the client kept its own handwritten copies — a mirror
list in `src/game/surfaces.js`, a bare `const CLS_ACERA = 6` in `c2d/flora.js`,
raw `=== 0` for water in six modules — and they had already drifted: the editor
knew 8 of 11 surfaces, `malecon` was missing from two palettes, and
`living_street` had no render rank at all — latent, because nothing is tagged
that way yet, which is exactly why it would have shipped.

So generate them instead. Generation is ONE-WAY and the artifacts are checked
in, because the game builds with Vite and must not need Python:

    churchill/world/enums/  ->  src/domain/vocabulary.generated.js   (the game)
                            ->  src/assets/vocabulary.generated.json (tools,
                                                                      editor)

Run `python3 tools/gen_vocabulary.py`; `--check` fails instead of writing, which
is what `tests/test_vocabulary.py` uses to keep the artifacts honest. Output is
deterministic — same enums, byte-identical files — for the same reason the world
build is.

A NAME here may be refactored freely; a VALUE may not. An emitted value is a
wire change, and for `Surface` it is a change to what every existing tile means.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from churchill.world.enums import editing, features, game  # noqa: E402
from churchill.world.enums.surface import (  # noqa: E402
    CALLE, CARRIAGEWAY, DRIVABLE, STREET, Surface, WALL,
)

JS_PATH = os.path.join(ROOT, "src", "domain", "vocabulary.generated.js")
JSON_PATH = os.path.join(ROOT, "src", "assets", "vocabulary.generated.json")

#: Bumped when the SHAPE of the artifact changes (an export added or renamed),
#: never for a new member — consumers read names, not a schema revision.
VOCABULARY_VERSION = 1

#: The named role sets from `enums/surface.py`. These are the lists a "can I
#: drive here", "is this a wall", "what is the nearest street" question reads,
#: and every one of them was a hand-rolled array on the client.
SURFACE_ROLES = (
    ("DRIVABLE", DRIVABLE),
    ("WALL", WALL),
    ("STREET", STREET),
    ("CARRIAGEWAY", CARRIAGEWAY),
    ("CALLE", CALLE),
)

#: Which enums cross into the client, and the const each becomes. Explicit
#: rather than introspected: this list is the review surface, and a new enum
#: should be a deliberate line here.
STR_ENUMS = (
    # what the world CONTAINS
    ("PARCEL_USE", features.ParcelUse),
    ("GREEN_TYPE", features.GreenType),
    ("LANDMARK_TYPE", features.LandmarkType),
    ("PATH_SURFACE", features.PathSurface),
    ("WEATHER", features.Weather),
    ("ROAD_CLASS", features.RoadClass),
    ("ISLAND_KIND", features.IslandKind),
    ("SIGN_KIND", features.SignKind),
    ("PIER_STYLE", features.PierStyle),
    ("LINE_END", features.LineEnd),
    ("FIELD_SPORT", features.FieldSport),
    # what the GAME branches on
    ("STAGE_KIND", game.StageKind),
    ("VEHICLE_MEDIUM", game.VehicleMedium),
    ("VEHICLE_KIND", game.VehicleKind),
    ("RENDERER_BACKEND", game.RendererBackend),
    ("GAME_MODE", game.GameMode),
    ("UI_SCREEN", game.UIScreen),
    ("COIN_TYPE", game.CoinType),
    ("CROSSING_OUTCOME", game.CrossingOutcome),
    ("ESTERO_ENCOUNTER", game.EsteroEncounterKind),
    ("NPC_MOVEMENT", game.NpcMovement),
    # what the EDITOR authors and the game reads back
    ("HOST_KIND", editing.HostKind),
    ("GEOMETRY_KIND", editing.GeometryKind),
    ("EDITOR_OPERATION", editing.EditorOperation),
)

#: The road-class role sets — two of them, on purpose. The audit found the
#: builder's "never yields" list and the client's "traffic may speed here" list
#: treated as one set that disagreed about `paseo`; they are two questions.
ROAD_ROLES = (
    ("YIELDS_TO", features.YIELDS_TO),
    ("TRAFFIC_MAIN", features.TRAFFIC_MAIN),
)

#: The sports that draw a COURT rather than a pitch. A role set rather than a
#: second enum, for the same reason the road ones are: it answers one question
#: about the members. `paintField` in src/render/c2d/streets.js had the pair as
#: two literals.
FIELD_SPORT_ROLES = (
    ("COURT", features.COURT_SPORTS),
)


def _js_object(pairs, indent="  "):
    body = "".join(f"{indent}{k}: {v},\n" for k, v in pairs)
    return "Object.freeze({\n" + body + "})"


def _js_array(values):
    return "Object.freeze([" + ", ".join(values) + "])"


def render_js():
    out = [
        "// GENERATED by tools/gen_vocabulary.py from churchill/world/enums/.",
        "// DO NOT EDIT: add the member to the Python enum and regenerate, or the",
        "// world and the client stop agreeing about what a tile byte means.",
        "//",
        "// The Surface values are the WIRE FORMAT — the bytes inside every tile's",
        "// RLE and the indices of `manifest.grid.classes`. Append, never renumber.",
        f"export const VOCABULARY_VERSION = {VOCABULARY_VERSION};",
        "",
        "// ---- surfaces: the grid's own vocabulary -----------------------------",
        "export const SURFACE = " + _js_object(
            [(s.name, str(int(s))) for s in Surface]) + ";",
        "",
        "// index = wire id, exactly as it ships in `manifest.grid.classes`.",
        "export const SURFACE_CLASSES = " + _js_array(
            [json.dumps(s.label) for s in Surface]) + ";",
        "",
        "export const SURFACE_BY_NAME = " + _js_object(
            [(s.label, str(int(s))) for s in Surface]) + ";",
        "",
        "// The named role sets. Membership is the question every caller actually",
        "// asks — `DRIVABLE` excludes the malecón on purpose (a promenade is",
        "// somewhere people walk), and `CALLE` excludes a muelle deck because a",
        "// deck is something you drive ON, not a street to link TO.",
        "export const SURFACE_ROLE = " + _js_object(
            [(name, _js_array([f"SURFACE.{s.name}" for s in members]))
             for name, members in SURFACE_ROLES]) + ";",
        "",
        "/** Does `cls` (a wire id) belong to the named role set? */",
        "export function hasSurfaceRole(role, cls) {",
        "  const members = SURFACE_ROLE[role];",
        "  return members !== undefined && members.includes(cls);",
        "}",
        "",
        "// ---- the token vocabularies the client switches on -------------------",
    ]
    for const, enum in STR_ENUMS:
        out.append(f"export const {const} = " + _js_object(
            [(m.name, json.dumps(str(m.value))) for m in enum]) + ";")
        out.append(f"export const {const}_VALUES = " + _js_array(
            [json.dumps(str(m.value)) for m in enum]) + ";")
        out.append("")
    out += [
        "// ---- roads: painting order and the two role sets ---------------------",
        "// A higher rank is stroked OVER a lower one. Every RoadClass has an",
        "// entry, which is the drift this replaced: `living_street` had none, so",
        "// one would fall to 0 and paint under the service roads. Nothing in the",
        "// map is tagged that way yet — which is why it would have shipped.",
        "export const ROAD_RANK = " + _js_object(
            [(json.dumps(str(cls.value)), str(rank))
             for cls, rank in features.RENDER_RANK.items()]) + ";",
        "",
        "export const ROAD_ROLE = " + _js_object(
            [(name, _js_array([json.dumps(str(c.value)) for c in members]))
             for name, members in ROAD_ROLES]) + ";",
        "",
        "// A cancha is drawn as a COURT or as a PITCH, and that is the only",
        "// distinction the renderer makes among the sports it knows.",
        "export const FIELD_SPORT_ROLE = " + _js_object(
            [(name, _js_array([json.dumps(str(c.value)) for c in sorted(members)]))
             for name, members in FIELD_SPORT_ROLES]) + ";",
    ]
    return "\n".join(out).rstrip("\n") + "\n"


def render_json():
    doc = {
        "_generated": "tools/gen_vocabulary.py from churchill/world/enums/ — "
                      "read-only; the Python enums are the authority",
        "version": VOCABULARY_VERSION,
        "surface": {
            "classes": [s.label for s in Surface],
            "byName": {s.label: int(s) for s in Surface},
            "roles": {name: [s.label for s in members]
                      for name, members in SURFACE_ROLES},
        },
        "enums": {const: [str(m.value) for m in enum]
                  for const, enum in STR_ENUMS},
        "field": {
            "roles": {name: sorted(str(c.value) for c in members)
                      for name, members in FIELD_SPORT_ROLES},
        },
        "road": {
            "rank": {str(cls.value): rank
                     for cls, rank in features.RENDER_RANK.items()},
            "roles": {name: [str(c.value) for c in members]
                      for name, members in ROAD_ROLES},
        },
    }
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


def main(argv):
    check = "--check" in argv
    stale = []
    for path, text in ((JS_PATH, render_js()), (JSON_PATH, render_json())):
        rel = os.path.relpath(path, ROOT)
        current = None
        if os.path.exists(path):
            with open(path, encoding="utf-8") as fh:
                current = fh.read()
        if current == text:
            print(f"[vocab] {rel} up to date")
            continue
        if check:
            stale.append(rel)
            continue
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text)
        print(f"[vocab] wrote {rel}")
    if stale:
        print("[vocab] STALE: " + ", ".join(stale) +
              " — run python3 tools/gen_vocabulary.py")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
